3.MVC/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('contact/', views.contact),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path("robots.txt", views.RobotsTxtView.as_view(content_type="text/plain"), name="robots"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

3.MVC/myblog/posts/urls.py
from django.urls import path
from . import views

app_name="posts"

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page"),
]

3.MVC/myblog/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register_view, name="register"),
    path('login', views.login_view, name="login")
]

3.MVC/myblog/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default="default.jpg", blank=True)

    def __str__(self):
        return self.title
    

3.MVC/myblog/users/models.py
from django.db import models

# Create your models here.

3.MVC/myblog/myblog/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

def homepage(request):
    #return HttpResponse("Головна сторінка")
    return render(request, "home.html")

def contact(request):
    # return HttpResponse("Контакти")
    return render(request, "contact.html")

class RobotsTxtView(TemplateView):
    template_name = "robots.txt"

3.MVC/myblog/posts/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', { 'posts': posts })

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', { 'post': post })

3.MVC/myblog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid ():
            form.save()
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request,"users/register.html", { "form": form })

def login_view(request):
    if request.method == "PULL":
        form = UserCreationForm(request.PULL)
        if form.is_valid ():
            form.save()
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request,"users/login.html", { "form": form })

3.MVC/myblog/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{post.title}}  
{% endblock %}

{% block content %}
    <h1 class="text-center">{{post.title}}</h1>
    <div class="container">
        <div class="bg-body-tertiary p-5 mb-3 rounded">
            <img 
                class="w-100"
                style="max-width: 800px"
                src="{{ post.banner.url }}" 
                alt="{{ post.title }}"/>
          <p class="lead">{{post.body}}</p>
          <p class="text-end" style="text-transform: lowercase;">{{post.date|date:"d F Y H:i"}}</p>
        </div>
    </main>
{% endblock %}

3.MVC/myblog/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Новини
{% endblock %}

{% block content %}
    <h1 class="text-center">Новини</h1>
    <div class="container">
        {% for post in posts %}
        <div class="bg-body-tertiary p-5 mb-3 rounded">
          <h3>{{post.title}}</h3>
          <p class="lead">{{post.body}}</p>
          <p class="text-end" style="text-transform: lowercase;">{{post.date|date:"d F Y H:i"}}</p>
          <a class="btn btn-lg btn-primary" href="{% url 'posts:page' slug=post.slug %}" role="button">Детальніше</a>
        </div>
        {% endfor %}
    </main>
{% endblock %}

3.MVC/myblog/templates/contact.html
{% extends "layout.html" %}

{% block title %}
    Контакти
{% endblock %}

{% block content %}
    <h1 class="text-center">Контакти</h1>
{% endblock %}

3.MVC/myblog/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Головна сторінка
{% endblock %}

{% block content %}
    <h1 class="text-center">Головна сторінка</h1>
{% endblock %}

3.MVC/myblog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Новини
        {% endblock %}
    </title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <header data-bs-theme="dark">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container">
            <a class="navbar-brand" href="/" aria-label="На головну">Головна</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'posts:list' %}">Новини</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/contact">Контакти</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
              </ul>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">Реєстрація</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'users:login' %}">Авторизація</a>
                </li>
              </ul>
              {% comment %} <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form> {% endcomment %}
            </div>
          </div>
        </nav>
    </header>
    
    <main>
        {% block content %}
        {% endblock %}
    
    </main>


    {% block scripts %}
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% endblock %}
</body>
</html>

3.MVC/myblog/users/templates/users/login.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Авторизація користувача
{% endblock %}

{% block content %}
    <h1 class="text-center">Авторизація</h1>
    <link rel="stylesheet" href="{% static 'css/authorization.css' %}">
    <div class="container " id="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" action="/users/register" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Ім'я користувача</label>
                        <input type="text" class="form-control" name="username" id="username" 
                            aria-describedby="usernameHelp"
                            pattern="[a-zA-Z0-9@.+_-]{1,150}$"
                            maxlength="150"
                            required>
                        <div class="invalid-feedback">
                            Необхідно: 150 або менше символів. тільки букви, цифри та знаки @/./+/-/_.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="password1" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password1" name="password1"
                        pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#\s*^&+]).{8,24}$" 
                        required
                    >
                        <div class="invalid-feedback">
                            <ul>
                                <li>Пароль має містити хоча б одну велику літеру.</li>
                                <li>Ваш пароль повинен містити як мінімум 8 символів.</li>
                                <li>Пароль має містити хоча б одну цифру.</li>
                                <li>Пароль має містити хоча б 1 спецсимвол ([!@#\s*^&+).</li>
                            </ul>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Авторизуватися</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

3.MVC/myblog/users/templates/users/register.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Реєстрація нового користувача  
{% endblock %}

{% block content %}
    <h1 class="text-center">Реєстрація</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" action="/users/register" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Ім'я користувача</label>
                        <input type="text" class="form-control" name="username" id="username" 
                            aria-describedby="usernameHelp"
                            pattern="[a-zA-Z0-9@.+_-]{1,150}$"
                            maxlength="150"
                            required>
                        <div class="invalid-feedback">
                            Необхідно: 150 або менше символів. тільки букви, цифри та знаки @/./+/-/_.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="password1" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password1" name="password1"
                        pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#\s*^&+]).{8,24}$" 
                        required
                    >
                        <div class="invalid-feedback">
                            <ul>
                                <li>Пароль має містити хоча б одну велику літеру.</li>
                                <li>Ваш пароль повинен містити як мінімум 8 символів.</li>
                                <li>Пароль має містити хоча б одну цифру.</li>
                                <li>Пароль має містити хоча б 1 спецсимвол ([!@#\s*^&+).</li>
                            </ul>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="password2" class="form-label">Підтвердження пароля</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                        <div class="invalid-feedback">
                            Паролі не збігаються.
                        </div>
                    </div>
                    {% comment %} {{ form }} {% endcomment %}
                    <button type="submit" class="btn btn-success">Реєструватися</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}